name: Borsa Robotu

on:
  schedule:
    - cron: '15 15 * * 1-5'
  workflow_dispatch:

jobs:
  analiz_yap:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Çek
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        
        # 1. Numpy sürümünü sabitle (Hata almamak için şart)
        pip install "numpy<2.0.0"
        
        # 2. Temel kütüphaneleri yükle
        pip install pandas requests yfinance scikit-learn xgboost lightgbm catboost
        
        # 3. GARANTİ ÇÖZÜM: pandas_ta'yı ZIP dosyası olarak indirip kuruyoruz.
        # Bu yöntem "Username/Password" hatasını %100 bypass eder.
        pip install https://github.com/twopirllc/pandas-ta/archive/refs/heads/development.zip

    - name: Dosyaları Kontrol Et
      run: ls -R

    - name: Robotu Çalıştır
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
