name: Borsa Robotu

on:
  schedule:
    - cron: '15 15 * * 1-5'
  workflow_dispatch:

jobs:
  analiz_yap:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Çek
      uses: actions/checkout@v3

    # Python 3.9 en kararlı sürümdür, bunu kullanacağız.
    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Zorla Kurulum Yap
      run: |
        # 1. Pip güncelle
        python -m pip install --upgrade pip
        pip install wheel setuptools
        
        # 2. Numpy'yi sabitle (Çok önemli)
        pip install "numpy<2.0.0"
        
        # 3. Standart kütüphaneleri kur
        pip install pandas requests yfinance scikit-learn xgboost lightgbm catboost
        
        # 4. PANDAS-TA İÇİN "KABA KUVVET" YÖNTEMİ
        # Link hatalarını aşmak için direkt wget ile indiriyoruz:
        echo "Kütüphane indiriliyor..."
        wget https://github.com/twopirllc/pandas-ta/archive/refs/heads/development.zip -O pandas_ta.zip
        
        echo "Zip açılıyor..."
        unzip pandas_ta.zip
        
        echo "Klasörden kurulum yapılıyor..."
        # Zip açılınca klasör adı 'pandas-ta-development' olur
        pip install ./pandas-ta-development

    - name: Robotu Çalıştır
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
